general:
  name: "fmbench-openai-gpt4o-large-prompts"      
  model_name: "gpt 4o"
  
# AWS and SageMaker settings
aws:
  region: {region}
  # uncomment and set the Role ARN if not running on sagemaker
  sagemaker_execution_role: {role_arn}
  ## these are the buckets/resources you will create in your account below:
  bucket: {write_bucket}

## WRITE BUCKET -- Write the results, data, metrics, endpoint.json and payloads to this bucket directory
dir_paths:
    data_prefix: data ## add the prefix for all your data management/storage
    prompts_prefix: prompts
    all_prompts_file: all_prompts.csv
    metrics_dir: metrics
    models_dir: models
    metadata_dir: metadata ## add a file here to dynamically track the metrics dir

## READ BUCKET -- Represents the section to read from scripts, source data and tokenizer for a separate s3 bucket for read/write segregation
s3_read_data:
    read_bucket: {read_bucket}
    scripts_prefix: scripts ## add your own scripts in case you are using anything that is not on jumpstart
    script_files:
    - hf_token.txt  ## add your scripts files you have in s3 (including inference files, serving stacks, if any)
    - openai_key.txt ## add your api keys for non aws models here so that they are used successfully during prediction
    - gemini_key.txt

    configs_prefix: configs
    config_files:
    - pricing.yml ## mention the name of the config files that you want to be downloaded from s3 into the configs directory locally
    source_data_prefix: source_data  ## Add a source_data folder to store your raw data in an s3 path configured by you
    source_data_files:
    - synthetic_data_large_prompts.jsonl
    tokenizer_prefix: tokenizer ## add the tokenizer.json and config.json from your specific tokenizer type
    prompt_template_dir: prompt_template
    prompt_template_file: prompt_template_openai_summarization.txt ## add your desired prompt template type

## section that enables container to run notebooks and python scripts automatically 
run_steps:
    0_setup.ipynb: yes
    1_generate_data.ipynb: yes
    2_deploy_model.ipynb: no
    3_run_inference.ipynb: no
    4_get_evaluations.ipynb: no
    5_model_metric_analysis.ipynb: yes
    6_cleanup.ipynb: no

datasets:
  prompt_template_keys:
  - input
  ground_truth_col_key: answers
  question_col_key: input
  filters:
  - language: en    
    min_length_in_tokens: 1
    max_length_in_tokens: 500
    payload_file: payload_en_1-500.jsonl
  - language: en
    min_length_in_tokens: 500
    max_length_in_tokens: 1500
    payload_file: payload_en_500-1500.jsonl
  - language: en
    min_length_in_tokens: 1500
    max_length_in_tokens: 2500
    payload_file: payload_en_1500-2500.jsonl
  - language: en
    min_length_in_tokens: 2500
    max_length_in_tokens: 3500
    payload_file: payload_en_2500-3500.jsonl
  - language: en
    min_length_in_tokens: 3500
    max_length_in_tokens: 4500
    payload_file: payload_en_3500-4500.jsonl
 
# name of the file that contains the model evaluation information
# for example, the prompt template names, the ground truth column name (if any), 
# LLM panelist information, inference parameters, etc.
model_evaluations: model_eval_all_info.yml


metrics:
  dataset_of_interest: en_2500-3500

  
pricing: pricing.yml ## mention the name of the file that contains pricing information, within s3 or locally in the configs folder
  
inference_parameters: 
  external:
    temperature: 0.1
    max_tokens: 300
    top_p: 0.92
    caching: False

# Model configurations for openAI models
experiments:
  - name: gpt-4o
    model_name: gpt-4o
    ep_name: gpt-4o
    instance_type: gpt-4o
    instance_count:
    inference_script: external_predictor.py
    inference_spec:
      split_input_and_parameters: no
      parameter_set: external
    payload_files:
    - payload_en_1-500.jsonl
    - payload_en_500-1500.jsonl
    - payload_en_1500-2500.jsonl
    - payload_en_2500-3500.jsonl
    - payload_en_3500-4500.jsonl
    concurrency_levels:
    - 1
    env:
    
report:
  latency_budget: 3
  cost_per_10k_txn_budget: 500
  error_rate_budget: 0
  per_inference_request_file: per_inference_request_results.csv
  all_metrics_file: all_metrics.csv
  txn_count_for_showing_cost: 10000
  v_shift_w_single_instance: 0.025
  v_shift_w_gt_one_instance: 0.025
