general:
  name: "mistral-7b-p5-instruct-AWQ"
  model_name: "mistral7bInstruct-AWQ"

# AWS and SageMaker settings
aws:
  region: {region}
  # uncomment and set the Role ARN if not running on sagemaker
  sagemaker_execution_role: {role_arn}
  ## these are the buckets/resources you will create in your account below:
  bucket: {write_bucket} ## add the name of your desired bucket

## WRITE BUCKET -- Write the results, data, metrics, endpoint.json and payloads to this bucket directory
dir_paths:
    data_prefix: data ## add the prefix for all your data management/storage
    prompts_prefix: prompts
    all_prompts_file: all_prompts.csv
    metrics_dir: metrics
    models_dir: models
    metadata_dir: metadata ## add a file here to dynamically track the metrics dir

## READ BUCKET -- Represents the section to read from scripts, source data and tokenizer for a separate s3 bucket for read/write segregation
s3_read_data:
    read_bucket: {read_bucket}
    scripts_prefix: scripts ## add your own scripts in case you are using anything that is not on jumpstart
    script_files:
    - hf_token.txt  ## add your scripts files you have in s3 (including inference files, serving stacks, if any)
    configs_prefix: configs
    config_files:
    - pricing.yml
    source_data_prefix: source_data  ## Add a source_data folder to store your raw data in an s3 path configured by you
    source_data_files:
    - 2wikimqa_e.jsonl
    - 2wikimqa.jsonl
    - hotpotqa_e.jsonl
    - hotpotqa.jsonl
    - narrativeqa.jsonl
    - triviaqa_e.jsonl
    - triviaqa.jsonl
    tokenizer_prefix: mistral_tokenizer ## add the tokenizer.json and config.json from your specific tokenizer type
    prompt_template_dir: prompt_template
    prompt_template_file: prompt_template_mistral.txt ## add your desired prompt template type

## section that enables container to run notebooks and python scripts automatically 
run_steps:
    0_setup.ipynb: yes
    1_generate_data.ipynb: yes
    2_deploy_model.ipynb: yes
    3_run_inference.ipynb: yes
    4_model_metric_analysis.ipynb: yes
    5_cleanup.ipynb: yes

datasets:
  prompt_template_keys:
  - input
  - context
  filters:
  - language: en    
    min_length_in_tokens: 1
    max_length_in_tokens: 500
    payload_file: payload_en_1-500.jsonl
  - language: en
    min_length_in_tokens: 500
    max_length_in_tokens: 1000
    payload_file: payload_en_500-1000.jsonl
  - language: en
    min_length_in_tokens: 1000
    max_length_in_tokens: 2000
    payload_file: payload_en_1000-2000.jsonl
  - language: en
    min_length_in_tokens: 2000
    max_length_in_tokens: 3000
    payload_file: payload_en_2000-3000.jsonl
  - language: en
    min_length_in_tokens: 3000
    max_length_in_tokens: 4000
    payload_file: payload_en_3000-4000.jsonl
  - language: en
    min_length_in_tokens: 305
    max_length_in_tokens: 3997
    payload_file: payload_en_305-3997.jsonl
  - language: en
    min_length_in_tokens: 1600
    max_length_in_tokens: 5000
    payload_file: payload_en_1600-5000.jsonl

metrics:
  dataset_of_interest: en_1000-2000
  
pricing: pricing.yml
  
inference_parameters:
  sagemaker:
    do_sample: yes
    temperature: 0.1
    top_p: 0.92
    top_k: 120  
    max_new_tokens: 100

# Model configurations
experiments:
  - name: mistral-Instruct7b-p5
    model_id: TheBloke/Mistral-7B-Instruct-v0.2-AWQ
    model_version: "*"
    model_name: mistral7bInstruct-AWQ
    ep_name: mistral7bInstruct-P5AWQ
    download_from_hf_place_in_s3: yes
    model_s3_path: s3://{write_bucket}/TheBloke/Mistral-7B-Instruct-v0.2-AWQ
    instance_type: "ml.p5.48xlarge"
    image_uri: 763104351884.dkr.ecr.{region}.amazonaws.com/djl-inference:0.26.0-deepspeed0.12.6-cu121
    deploy: yes
    instance_count: 1
    deployment_script: deploy_w_djl_serving.py
    inference_script: sagemaker_predictor.py
    inference_spec:
      parameter_set: sagemaker
    serving.properties: |
      engine=Python
      option.tensor_parallel_degree=1
      option.model_id=s3://{write_bucket}/TheBloke/Mistral-7B-Instruct-v0.2-AWQ
      option.max_rolling_batch_size=64
      option.rolling_batch=vllm
    payload_files:
    - payload_en_1000-2000.jsonl
    concurrency_levels:
    - 1
    - 2
    - 5
    - 10
    - 20
    - 30
    env:

report:
  latency_budget: 1
  cost_per_10k_txn_budget: 20
  error_rate_budget: 0
  per_inference_request_file: per_inference_request_results.csv
  all_metrics_file: all_metrics.csv
  txn_count_for_showing_cost: 10000
  v_shift_w_single_instance: 0.025
  v_shift_w_gt_one_instance: 0.025
  latency_vs_token_len_chart: 
    y_ticks: 
    # - 1
    # - 2
    # - 3
    # - 4
    title: "Effect of token length on inference latency for \"TheBloke/Mistral-7B-Instruct-v0.2-AWQ\""

