general:
  name: "fmbench-bedrock-nova-models"
  model_name: "Nova models available in Amazon Bedrock"

aws:
  region: {region}
  sagemaker_execution_role: {role_arn}
  bucket: {write_bucket}

dir_paths:
  data_prefix: data
  prompts_prefix: prompts
  all_prompts_file: all_prompts.csv
  metrics_dir: metrics
  models_dir: models
  metadata_dir: metadata

s3_read_data:
  read_bucket: {read_bucket}
  scripts_prefix: scripts
  script_files:
    - hf_token.txt
  configs_prefix: configs
  config_files:
    - pricing.yml
  source_data_prefix: source_data
  source_data_files:
    - 2wikimqa_e.jsonl
    - 2wikimqa.jsonl
    - hotpotqa_e.jsonl
    - hotpotqa.jsonl
    - narrativeqa.jsonl
    - triviaqa_e.jsonl
    - triviaqa.jsonl
  tokenizer_prefix: tokenizer
  prompt_template_dir: prompt_template
  prompt_template_file: prompt_template_nova.txt

run_steps:
  0_setup.ipynb: yes
  1_generate_data.ipynb: yes
  2_deploy_model.ipynb: no
  3_run_inference.ipynb: yes
  4_get_evaluations.ipynb: yes
  5_model_metric_analysis.ipynb: yes
  6_cleanup.ipynb: no

datasets:
  prompt_template_keys:
    - input
    - context
  ground_truth_col_key: answers
  question_col_key: input
  filters:
    - language: en
      min_length_in_tokens: 1
      max_length_in_tokens: 500
      payload_file: payload_en_1-500.jsonl
    - language: en
      min_length_in_tokens: 500
      max_length_in_tokens: 1000
      payload_file: payload_en_500-1000.jsonl
    - language: en
      min_length_in_tokens: 1000
      max_length_in_tokens: 2000
      payload_file: payload_en_1000-2000.jsonl
    - language: en
      min_length_in_tokens: 2000
      max_length_in_tokens: 3000
      payload_file: payload_en_2000-3000.jsonl
    - language: en
      min_length_in_tokens: 3000
      max_length_in_tokens: 4000
      payload_file: payload_en_3000-4000.jsonl
    - language: en
      min_length_in_tokens: 4000
      max_length_in_tokens: 5000
      payload_file: payload_en_4000-5000.jsonl
    - language: en
      min_length_in_tokens: 5000
      max_length_in_tokens: 6000
      payload_file: payload_en_5000-6000.jsonl

model_evaluations: model_eval_all_info.yml

metrics:
  dataset_of_interest: en_5000-6000

pricing: pricing.yml

inference_parameters:
  bedrock:
    temperature: 0.1
    max_tokens: 100
    top_p: 0.92
    caching: false
    use_boto3: yes

# Define repeated fields for experiments in a YAML anchor.
experiments_defaults: &bedrock_experiment
  inference_script: bedrock_predictor.py
  instance_count:
  inference_spec:
    split_input_and_parameters: no
    parameter_set: bedrock
  payload_files:
    - payload_en_1-500.jsonl
    - payload_en_500-1000.jsonl
    - payload_en_1000-2000.jsonl
    - payload_en_2000-3000.jsonl
    - payload_en_3000-4000.jsonl
    - payload_en_4000-5000.jsonl
    - payload_en_5000-6000.jsonl
  concurrency_levels:
    - 1
  env:

experiments:
  - <<: *bedrock_experiment
    name: amazon.nova-micro-v1:0
    model_name: amazon.nova-micro-v1:0
    ep_name: amazon.nova-micro-v1:0
    instance_type: amazon.nova-micro-v1:0

  - <<: *bedrock_experiment
    name: amazon.nova-lite-v1:0
    model_name: amazon.nova-lite-v1:0
    ep_name: amazon.nova-lite-v1:0
    instance_type: amazon.nova-lite-v1:0

  - <<: *bedrock_experiment
    name: amazon.nova-pro-v1:0
    model_name: amazon.nova-pro-v1:0
    ep_name: amazon.nova-pro-v1:0
    instance_type: amazon.nova-pro-v1:0

report:
  latency_budget: 2
  cost_per_10k_txn_budget: 20
  error_rate_budget: 0
  per_inference_request_file: per_inference_request_results.csv
  all_metrics_file: all_metrics.csv
  txn_count_for_showing_cost: 10000
  v_shift_w_single_instance: 0.025
  v_shift_w_gt_one_instance: 0.025
